### ISSUE TITLE
Download a range of episodes

### ISSUE THREAD

**Issue by ZReC** [yashas123/animepahe-downloader#2]
Your app does its job well, but it can be _weller_ if it were possible to download a range of episodes instead of downloading the whole serie (maybe I'm wrong and that feature does already exist but I didn't realize).

Whatevs, it's just an idea that sounds great for large series, those can weigh a lot.
Thanks for your work, I really appreciate it.

**Comment by modbender** [comment]
I do plan to do that by creating GUI for the app.

**Comment by uali6981** [comment]
Yeah.
So many thanks for this new update with awesome GUI and features.
